class modManager{
    constructor(layer,battle){
        this.layer=layer
        this.battle=battle
        this.mods=[]
        this.holdMod=[]
        this.listing={mod:[]}
        this.createListing()
        for(let a=0,la=5;a<la;a++){
            //this.addMod(15+a)
        }
    }
    createListing(){
        for(let a=0,la=types.mod.length;a<la;a++){
            this.mods.push(false)
            this.listing.mod.push(a)
        }
    }
    addMod(type){
        this.mods[type]=true
        this.holdMod.push(type)
    }
    display(){
        if(variants.mod){
            this.layer.fill(200,this.fade)
            this.layer.noStroke()
            this.layer.ellipse(this.layer.width-25,250,40,40)
            this.layer.stroke(100,this.fade)
            this.layer.strokeWeight(2)
            this.layer.quad(this.layer.width-19,240,this.layer.width-11,240,this.layer.width-31,260,this.layer.width-39,260)
        }
    }
    onClick(){
        if(dist(inputs.rel.x,inputs.rel.y,this.layer.width-25,250)<20){
            this.battle.overlayManager.overlays[41][0].active=true
            this.battle.overlayManager.overlays[41][0].activate()
        }
    }
    onKey(key,code){
        if(key=='m'){
            this.battle.overlayManager.overlays[41][0].active=true
            this.battle.overlayManager.overlays[41][0].activate()
        }
    }
}