types={
    card:[
        {
            name:'',
            stats:[
                {},
            ],
        },{
            name:'Strike',
            stats:[
                {},
            ],
        },{
            name:'Defend',
            stats:[
                {},
            ],
        },{
            name:'Step',
            stats:[
                {},
            ],
        },
    ],combatant:[
        {life:0},
        {life:60},
    ],color:[
        {
            fill:[150,200,150],
            stroke:[125,175,125],
        },
    ],
}
stage={scale:0,scene:'battle'}
game={player:1,id:0,timer:0}
graphics={main:0,minor:[],combatant:[]}
transition={trigger:false,anim:0,scene:stage.scene}
inputs={mouse:{x:0,y:0},rel:{x:0,y:0},keys:[[false,false,false,false],[false,false,false,false]]}
a=0;b=0;c=0;d=0;e=0;f=0;g=0;h=0;i=0;j=0;k=0;l=0;m=0;n=0;o=0;p=0
la=0;lb=0;lc=0;ld=0;le=0;lf=0;lg=0;lh=0;li=0;lj=0;lk=0;ll=0;lm=0;ln=0;lo=0;lp=0