types={
    card:[
        {
            name:'',
            levels:[
                {effect:[0],attack:0,cost:0,target:[0],spec:[],class:0},
                {effect:[0],attack:0,cost:0,target:[0],spec:[],class:0},
            ],
        },{
            name:'Strike',
            levels:[
                {effect:[6],attack:1,cost:1,target:[2,1,1],spec:[0],class:1},
                {effect:[9],attack:1,cost:1,target:[2,1,1],spec:[0],class:1},
            ],
        },{
            name:'Defend',
            levels:[
                {effect:[8],attack:2,cost:1,target:[0],spec:[],class:2},
                {effect:[12],attack:2,cost:1,target:[0],spec:[],class:2},
            ],
        },{
            name:'Step',
            levels:[
                {effect:[1],attack:3,cost:1,target:[1,1,1],spec:[],class:3},
                {effect:[1],attack:3,cost:0,target:[1,1,1],spec:[],class:3},
            ],
        },{
            name:'Twin\nStrike',
            levels:[
                {effect:[5],attack:4,cost:1,target:[2,1,1],spec:[0],class:1},
                {effect:[7],attack:4,cost:1,target:[2,1,1],spec:[0],class:1},
            ],
        },{
            name:'Long\nStrike',
            levels:[
                {effect:[7],attack:1,cost:1,target:[2,1,2],spec:[0],class:1},
                {effect:[10],attack:1,cost:1,target:[2,1,2],spec:[0],class:1},
            ],
        },{
            name:'Dash',
            levels:[
                {effect:[2],attack:3,cost:1,target:[1,1,2],spec:[],class:3},
                {effect:[3],attack:3,cost:1,target:[1,1,3],spec:[],class:3},
            ],
        },{
            name:'Push',
            levels:[
                {effect:[0],attack:5,cost:0,target:[2,1,1],spec:[],class:1},
                {effect:[4],attack:5,cost:0,target:[2,1,1],spec:[],class:1},
            ],
        },{
            name:'Wind\nUp',
            levels:[
                {effect:[1],attack:6,cost:1,target:[0],spec:[],class:4},
                {effect:[2],attack:6,cost:1,target:[0],spec:[],class:4},
            ],
        },{
            name:'Chain',
            levels:[
                {effect:[8,1],attack:7,cost:1,target:[2,1,1],spec:[0],class:1},
                {effect:[12,1],attack:7,cost:1,target:[2,1,1],spec:[0],class:1},
            ],
        },{
            name:'Think',
            levels:[
                {effect:[3],attack:8,cost:1,target:[0],spec:[],class:4},
                {effect:[4],attack:8,cost:1,target:[0],spec:[],class:4},
            ],
        },

        {
            name:'Fatigue',
            levels:[
                {effect:[],attack:0,cost:1,target:[0],spec:[1],class:5},
                {effect:[],attack:0,cost:1,target:[0],spec:[1],class:5},
            ],
        },
    ],combatant:[
        {name:'',life:20,behavior:0,move:{type:0,speed:0},attack:[{type:0,effect:[]}],description:""},
        {name:'Lira',life:60,behavior:0,move:{type:0,speed:0},attack:[],description:"Swordfighting apprentice from Konai.\nThis is her last chance to survive.\nWhatever it might take to accomplish,\nshe will defeat the Management."},
        {name:'Rat',life:10,behavior:0,move:{type:0,speed:1},attack:[{type:1,effect:[4]}],description:""},
    ],color:{
        card:[
            {
                fill:[200,200,200],
                stroke:[175,175,175],
                text:[50,50,50],
                active:[255,255,255],
            },{
                fill:[150,200,150],
                stroke:[125,175,125],
                text:[0,100,0],
                active:[200,255,200],
            },{
                fill:[125,125,125],
                stroke:[100,100,100],
                text:[40,40,40],
                active:[200,200,200],
            },
        ],
    },deck:{
        start:[
            //[['Wind\nUp',0,0],['Chain',0,0],['Think',0,0],['Step',0,0],['Dash',0,0]],
            [['Strike',0,0],['Strike',0,0],['Strike',0,0],['Strike',0,0],['Defend',0,0],['Defend',0,0],['Defend',0,0],['Defend',0,0],['Step',0,0],['Step',0,0],['Step',0,0],['Step',0,0]],
            [['Strike',0,1],['Strike',0,1],['Strike',0,1],['Strike',0,1],['Defend',0,1],['Defend',0,1],['Defend',0,1],['Defend',0,1],['Step',0,1],['Step',0,1],['Step',0,1],['Step',0,1]],
           
        ]
    },level:[
        {
            map:[
                [{type:0},{type:0},{type:0},{type:0},{type:-1},{type:-1},{type:-1}],
                [{type:0},{type:0},{type:0},{type:0},{type:0},{type:-1},{type:-1}],
                [{type:0},{type:0},{type:0},{type:0},{type:0},{type:0},{type:-1}],
                [{type:0},{type:0},{type:0},{type:0},{type:0},{type:0},{type:0}],
                [{type:-1},{type:0},{type:0},{type:0},{type:0},{type:0},{type:0}],
                [{type:-1},{type:-1},{type:0},{type:0},{type:0},{type:0},{type:0}],
                [{type:-1},{type:-1},{type:-1},{type:0},{type:0},{type:0},{type:0}],
            ],
        },
    ]
}
stage={scale:0,scene:'battle'}
game={player:0,playerNumber:1,id:0,timer:0,animRate:1,targetRadius:30,turnTime:0}
constants={collisionDamage:4}
graphics={main:0,minor:[],combatant:[]}
transition={trigger:false,anim:0,scene:stage.scene}
inputs={mouse:{x:0,y:0},rel:{x:0,y:0},above:'!@#$%^&*()',lastKey:''}
a=0;b=0;c=0;d=0;e=0;f=0;g=0;h=0;i=0;j=0;k=0;l=0;m=0;n=0;o=0;p=0
la=0;lb=0;lc=0;ld=0;le=0;lf=0;lg=0;lh=0;li=0;lj=0;lk=0;ll=0;lm=0;ln=0;lo=0;lp=0